version: 2
updates:
  # JavaScript / TypeScript
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Java / Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Go Modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Rust / Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Ruby / Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  # PHP / Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions (workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
