blank_issues_enabled: false

contact_links:
  - name: "💬 Community Support"
    url: "https://github.com/TechQuanta/discussions"
    about: "Ask general questions or get help from the community."

  - name: "🧠 Documentation / Wiki"
    url: "https://github.com/TechQuanta/wiki"
    about: "Read project and community documentation."
